"""Modelo inicial

Revision ID: 82f1e6f726bd
Revises: 
Create Date: 2026-07-17 04:28:20.127161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f1e6f726bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleados',
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=10), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('cargo', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_empleado'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('puestos',
    sa.Column('id_puesto', sa.Integer(), nullable=False),
    sa.Column('nombre_puesto', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_puesto')
    )
    op.create_table('dispositivos',
    sa.Column('id_dispositivo', sa.Integer(), nullable=False),
    sa.Column('codigo_dispositivo', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_puesto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_puesto'], ['puestos.id_puesto'], ),
    sa.PrimaryKeyConstraint('id_dispositivo'),
    sa.UniqueConstraint('codigo_dispositivo')
    )
    op.create_table('turnos',
    sa.Column('id_turno', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('id_puesto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], ),
    sa.ForeignKeyConstraint(['id_puesto'], ['puestos.id_puesto'], ),
    sa.PrimaryKeyConstraint('id_turno')
    )
    op.create_table('asistencias',
    sa.Column('id_asistencia', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('id_turno', sa.Integer(), nullable=False),
    sa.Column('id_dispositivo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['dispositivos.id_dispositivo'], ),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], ),
    sa.ForeignKeyConstraint(['id_turno'], ['turnos.id_turno'], ),
    sa.PrimaryKeyConstraint('id_asistencia')
    )
    op.create_table('novedades',
    sa.Column('id_novedad', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('id_turno', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], ),
    sa.ForeignKeyConstraint(['id_turno'], ['turnos.id_turno'], ),
    sa.PrimaryKeyConstraint('id_novedad')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('novedades')
    op.drop_table('asistencias')
    op.drop_table('turnos')
    op.drop_table('dispositivos')
    op.drop_table('puestos')
    op.drop_table('empleados')
    # ### end Alembic commands ###
