"""Agregar password_hash

Revision ID: f11e05b3b0f5
Revises: 82f1e6f726bd
Create Date: 2026-07-19 00:45:17.705323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11e05b3b0f5'
down_revision = '82f1e6f726bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
